all:
	cd CircuitRouter-SeqSolver && make
	cd CircuitRouter-ParSolver && make
	cd CircuitRouter-SimpleShell && make
clean:
	cd CircuitRouter-SeqSolver && make clean
	cd CircuitRouter-ParSolver && make clean
	cd CircuitRouter-SimpleShell && make clean
